# fly.toml app configuration file generated for braidcert on 2023-06-26T12:13:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "braidcert"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true

[mounts]
  source = "certs"
  destination = "/certs/"
